server:
  port: 30000
spring:
  cloud:
    alicloud:
      access-key: LTAIK1sIjeCnLntB
      secret-key: SF57wP9LjPoRsE9ikT4byeJO93RNTB
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: guli-mall-01

      sms:
        host: http://dingxin.market.alicloudapi.com
        path: /dx/sendSms
        appCode: 60585ae5a76445b8badf93f727d36ec1
        tpl_id: TP1711063


